apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replication-controller
  labels:
    app: myapp-replication-controller
    type: front-end
spec:
# Here we are using the template of the pod that we created earlier from pod-definition.yaml. This only includes the specification of the pod starting from the metadata and the spec section.
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-pod
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
# This is the number of replicas that we want to create. Here we are creating 3 replicas of the pod.